#ifndef FLIGHTSTATUS_H
#define FLIGHTSTATUS_H

enum FlightStatus {
    IDLE,
    IDLE_LAUNCH_READY,
    DATA_RECORDING,
    IN_FLIGHT_ASCENT,
    IN_FLIGHT_APOGEE,
    IN_FLIGHT_MAIN_CHUTE_DEPLOYED,
    LANDED,
    ERROR,
    ERROR_NO_SD
};

#endif