#ifndef FLIGHTSTATUS_H
#define FLIGHTSTATUS_H

enum FlightStatus {
    IDLE,
    CALIBRATED_LAUNCH_READY,
    SENSOR_CALIBRATION_AND_SD_WRITE,
    IN_FLIGHT_ASCENT,
    IN_FLIGHT_APOGEE,
    IN_FLIGHT_MAIN_CHUTE_DEPLOYED,
    LANDED,
    ERROR,
    ERROR_NO_SD
};

#endif